mkdir -p /Users/michael/GIT/rust/splitr/src/test_tests

# Create a new test file
cat <<EOT >> /Users/michael/GIT/rust/splitr/src/test_tests/test_splitr.rs
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_example() {
        assert_eq!(2 + 2, 4);
    }
}
EOT

# Setup a pipeline to test the code
cat <<EOT >> /Users/michael/GIT/rust/splitr/.github/workflows/rust.yml
name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
EOT