name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/splitr .

      - name: Push the image to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: https://index.docker.io/v1/

      - name: Create a tag for GitHub Packages
        run: |
          echo "splitr:latest" >> package.json

      - name: Upload the image to GitHub Packages
        uses: actions/upload-artifact@v3
        with:
          name: ${{ secrets.DOCKER_USERNAME }}/your-image-name
          path: your-image-name:latest
          packaging: zipest=/tmp/.buildx-cache
